import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <HeaderLayout></HeaderLayout>
      <body className={inter.className}>{children}</body>
    </html>
  );
}

export function HeaderLayout() {
  return (
    <header className={styles.header}>
      <h1 className={gothic.className}>Note App</h1>
      <nav className={styles.nav}>
        <Link href="/contact">Contact</Link>
        <Link href="/about">About</Link>
        <Link href="/product">Products</Link>
      </nav>
    </header>
  );
}
